### PR TITLE
Fix to avoid undesired multiple captures

### PR DESCRIPTION
**Pull request by makowildcat**
Add one missing state update.
In relation to issues #6 and #62

### CODE REVIEW

**Comment by makowildcat** [comment]
I signed it!

**Review by olgn — APPROVED** [review]
confirmed that this DOES fix a pretty serious bug in the application. why has this not been merged?

**Comment by jeffmcnd** [comment]
I can also confirm that this fixes things. Who has writes to merge?

**Review by jeffmcnd — APPROVED** [review]

**Comment by Shmarkus** [comment]
Still not merged!? WTH!

**Comment by raaviswami** [comment]
This breaks flash light in pixel2xl

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories

**Pull request closed without merging**
