### PR TITLE
Resolved crashing issue when user deny Camera Permission

### PR DESCRIPTION
**Pull request by ShreyashPromact**
When the user opens app very first time, or when the permission is not allowed and open the app, It will ask the user for approving permission for camera access. If the user denies the permission, the app gets crashed. It is resolved now.

### CODE REVIEW

**Comment by ShreyashPromact** [comment]
Hi, 
May I know, Why this commit is not approved?

Sincerely,
Shreyash

**Comment by ShreyashPromact** [comment]
Any updates on this?

**Comment by ShreyashPromact** [comment]
Is there any update on this?

**Comment by ShreyashPromact** [comment]
@googlebot 
Is there any update on this PR?

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories

**Pull request closed without merging**
