### PR TITLE
Added function to show image in gallery as well

### PR DESCRIPTION
**Pull request by ShreyashPromact**
Added function that will broadcast image. So that you can view same in Gallery as well.

### CODE REVIEW

**Comment by ShreyashPromact** [comment]
What's wrong with this commit? I am waiting for it to get accepted.

**Comment by goodbye-nightmare** [comment]
Why do you add so much files in this patch? Except the file "Camera2BasicFragment.java",  what is the role of other files?

**Comment by ShreyashPromact** [comment]
@goodbye-nightmare I have not added it. But it is added by default as because there is not .gitignore file added in the repository.

Should I add that and commit again?

**Comment by goodbye-nightmare** [comment]
@ShreyashPromact Oh, I see. This sample is missed the ".gitignore" file when pushed to the github. But I think in this solution, even add the ".gitignore" file to this project, this ".gitignore" file is also not valid.
I suggest that you re-clone a branch, modify only the relevant code, and then submit it.

**Comment by ShreyashPromact** [comment]
@goodbye-nightmare 
ok. Let me re-commit with adding .gitignore file in it.

**Comment by goodbye-nightmare** [comment]
@ShreyashPromact I think you don't need to add the ".gitignore" file. You just re-commit the "Camera2BasicFragment.java" is OK.
The file ".gitignore" is not relevant to your function.

**Comment by ShreyashPromact** [comment]
@goodbye-nightmare I hope it's fine now.

**Comment by ShreyashPromact** [comment]
Let me know if its not fine, I will re-commit for same.

Sincerely,
Shreyash

**Comment by ShreyashPromact** [comment]
@goodbye-nightmare 
any updates?

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories

**Pull request closed without merging**
